const openai = require("../config/openaiConfig");

exports.generateEmail = async (req, res, next) => {
  try {
    const { rawThoughts, tone, replyingTo } = req.body;
    if (!rawThoughts || !tone) {
      return res.status(400).json({
        success: false,
        message: "Missing required fields: rawThoughts and tone are required",
      });
    }

    let prompt = `You are an expert email writer. Transform the following raw thoughts into a well-written email with a ${tone} tone.
        
        Raw thoughts: ${rawThoughts}`;

    if (replyingTo && replyingTo.trim()) {
      prompt += `\n\nThis is in response to the following email:\n${replyingTo}`;
    }

    prompt += `\n\nImportant guidelines:
        - Write ONLY the email body content, no subject line
        - Use appropriate formatting with paragraphs
        - Match the ${tone} tone precisely
        - Keep it natural and human
        - Do not include greetings like "Dear [Name]" or signatures unless mentioned
        - Start directly with email content`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [
        {
          role: "system",
          content:
            "You are an expert email writer who helps to transform casual thoughts into polished, professional emails.",
        },
        { role: "user", content: prompt },
      ],

      temperature: 0.7,
      max_tokens: 1000,
    });

    const emailContent = completion.choices?.[0].message?.content?.trim();

    if (!emailContent) {
      return res.status(500).json({
        success: false,
        message:
          "OpenAI returned empty content. Check your prompt or API usage.",
      });
    }

    res.status(200).json({
      success: true,
      email: emailContent,
      tone,
    });
  } catch (error) {
    console.error("Error generated by email:", error);
    next(error);
  }
};
